---
 - name: Create Storage directory
   file:
     path: "{{ item }}"
     state: directory
     recurse: yes
   with_items:
   - {dir: '/storage/observability/grafana/'}

 - name: Create Storage subdirectory
   file:
     path: "{{ item.dir }}"
     state: directory
     owner: "{{ item.owner }}"
   with_items:
   - {dir: '/storage/observability/grafana/', owner: '472'}
   - {dir: '/storage/observability/grafana/provisioning/', owner: '472'}
   - {dir: '/storage/observability/grafana/provisioning/datasources/', owner: '472'}
   - {dir: '/storage/observability/grafana/provisioning/dashboards/', owner: '472'}

 - name: copy Docker Compose files
   template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
   with_items:
   - {src: 'grafana-compose.yaml.j2',dest: '/storage/observability/grafana-compose.yaml'}
   - {src: 'datasources.yaml.j2',dest: '/storage/observability/grafana/provisioning/datasources/datasources.yaml'}
   - {src: 'dashboards.yaml.j2',dest: '/storage/observability/grafana/provisioning/dashboards/dashboards.yaml'}
   notify: Restart grafana

 - name: copy files
   copy:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
   with_items:
   - {src: 'host.json',dest: '/storage/observability/grafana/provisioning/dashboards/host.json'}
   - {src: 'LOKI.json',dest: '/storage/observability/grafana/provisioning/dashboards/LOKI.json'}
   - {src: 'containers.json',dest: '/storage/observability/grafana/provisioning/dashboards/containers.json'}
   notify: Restart grafana

 - name: Enable grafana
   docker_compose:
     project_src: /storage/observability
     files:
     - grafana-compose.yaml
