---
  alertmanager_version: "v0.24.0"
  mail_to: "example@domain.org"
  cadvisor_version: "v0.33.0"
  grafana_version: "8.4.5"
  loki_version: "main-a9ac01b"
  nodeexporter_version: "v1.3.1"
  prometheus_version: "v2.34.0"
  auth_username: "{{ vault_auth_username }}"
  auth_password: "{{ vault_auth_password }}"
  smarthost: "{{ vault_smarthost }}"
  grafana_user: "{{ vault_grafana_user }}"
  grafana_pass: "{{ vault_grafana_pass }}"
  docker_required_packages:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg-agent"
    - "software-properties-common"
    - "python3-pip"
    - "python3-setuptools"
  docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
  docker_repo: deb https://download.docker.com/linux/ubuntu focal stable
  docker_packges:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
  docker_compose_url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64
