{
 "title": "Basic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance,mode) * 100",
     "legendFormat": "{{ instance }} {{ mode }}"
    },
    {
     "expr": "avg (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance,mode) * 100",
     "legendFormat": "{{ instance }} {{ mode }}"
    }
   ]
  },
  {
   "title": "CPU by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory usage by host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{internal_net=\"true\",image!=\"\"}) by (internal_net,instance) / sum(machine_memory_bytes{internal_net=\"true\"}) by (internal_net,instance) * 100",
     "legendFormat": "Total percent usage {{ instance }}"
    },
    {
     "expr": "machine_memory_bytes{internal_net=\"true\"}",
     "legendFormat": "TOTAL {{ instance }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{internal_net=\"true\",image!=\"\"}) by (instance)",
     "legendFormat": "Total contaners usage  {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{internal_net=\"true\",image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk usage on host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device) / sum(container_fs_limit_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device) * 100",
     "legendFormat": "Percent usage {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum(container_fs_limit_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device)",
     "legendFormat": "Total {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device)",
     "legendFormat": "Usage {{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "Disk usage by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{internal_net=\"true\",image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Reads / Writes disks by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{id=\"/\",internal_net=\"true\",device!=\"\"}[1m])",
     "legendFormat": "writes {{ instance }}_{{ device }}"
    },
    {
     "expr": "rate(container_fs_reads_bytes_total{id=\"/\",internal_net=\"true\",device!=\"\"}[1m])",
     "legendFormat": "reads {{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "Reads / Writes disks by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "writes {{ name }}_{{ device }}"
    },
    {
     "expr": "rate(container_fs_reads_bytes_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "read {{ name }}_{{ device }}"
    }
   ]
  },
  {
   "title": "Traffic on real iface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m]) * 8",
     "legendFormat": "transmit {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m]) * 8",
     "legendFormat": "received {{ instance }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Traffic by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{internal_net=\"true\",image!=\"\"}[1m]) * 8 ",
     "legendFormat": "transmit {{ name }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{internal_net=\"true\",image!=\"\"}[1m]) * 8",
     "legendFormat": "received {{ name }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Packets on real iface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m])",
     "legendFormat": "transmit {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_packets_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m])",
     "legendFormat": "received {{ instance }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Packets by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "transmit {{ name }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_packets_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "received {{ name }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Errors and drops packet on iface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_errors_total{internal_net=\"true\",id=\"/\",interface!~\"br.*\"}[1m])",
     "legendFormat": "transmit errors {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_errors_total{internal_net=\"true\",id=\"/\",interface!~\"br.*\"}[1m])",
     "legendFormat": "received errors {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_transmit_packets_dropped_total{internal_net=\"true\",id=\"/\",interface!~\"br.*\"}[1m])",
     "legendFormat": "transmit drop {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_packets_dropped_total{internal_net=\"true\",id=\"/\",interface!~\"br.*\"}[1m])",
     "legendFormat": "received drop {{ instance }}_{{ interface }}"
    }
   ]
  }
 ]
}