{
 "title": "Containers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{internal_net=\"true\",image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk usage by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{internal_net=\"true\",image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Reads / Writes disks by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "writes {{ name }}_{{ device }}"
    },
    {
     "expr": "rate(container_fs_reads_bytes_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "read {{ name }}_{{ device }}"
    }
   ]
  },
  {
   "title": "Traffic by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{internal_net=\"true\",image!=\"\"}[1m]) * 8 ",
     "legendFormat": "transmit {{ name }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{internal_net=\"true\",image!=\"\"}[1m]) * 8",
     "legendFormat": "received {{ name }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Packets by containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "transmit {{ name }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_packets_total{internal_net=\"true\",image!=\"\"}[1m])",
     "legendFormat": "received {{ name }}_{{ interface }}"
    }
   ]
  }
 ]
}