{
 "title": "Host monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance,mode) * 100",
     "legendFormat": "{{ instance }} {{ mode }}"
    },
    {
     "expr": "avg (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance,mode) * 100",
     "legendFormat": "{{ instance }} {{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Saturation(Load Average1)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "max(node_load1) by (instance)", "legendFormat": "{{ instance }}  load_average1" },
    {
     "expr": "count by (instance) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "{{ instance }} cores"
    }
   ]
  },
  {
   "title": "Memory usage by host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{internal_net=\"true\",image!=\"\"}) by (internal_net,instance) / sum(machine_memory_bytes{internal_net=\"true\"}) by (internal_net,instance) * 100",
     "legendFormat": "Total percent usage {{ instance }}"
    },
    {
     "expr": "machine_memory_bytes{internal_net=\"true\"}",
     "legendFormat": "TOTAL {{ instance }}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{internal_net=\"true\",image!=\"\"}) by (instance)",
     "legendFormat": "Total contaners usage  {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(node_vmstat_pgmajfault[1m])) by (instance)",
     "legendFormat": "{{ instance }} page  major faults"
    },
    {
     "expr": "sum(rate(node_vmstat_pgpgin[1m])) by (instance)",
     "legendFormat": "{{ instance }} page in"
    },
    {
     "expr": "sum(rate(node_vmstat_pgpgout[1m])) by (instance)",
     "legendFormat": "{{ instance }} page out"
    },
    {
     "expr": "sum(rate(node_vmstat_pswpin[1m])) by (instance)",
     "legendFormat": "{{ instance }} page swap in"
    },
    {
     "expr": "sum(rate(node_vmstat_pswpout[1m])) by (instance)",
     "legendFormat": "{{ instance }} page swap out"
    }
   ]
  },
  {
   "title": "Disk usage on host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device) / sum(container_fs_limit_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device) * 100",
     "legendFormat": "Percent usage {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum(container_fs_limit_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device)",
     "legendFormat": "Total {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",device=~\"/dev.*\",internal_net=\"true\"}) by (instance,device)",
     "legendFormat": "Usage {{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "Reads / Writes disks by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{id=\"/\",internal_net=\"true\",device!=\"\"}[1m])",
     "legendFormat": "writes {{ instance }}_{{ device }}"
    },
    {
     "expr": "rate(container_fs_reads_bytes_total{id=\"/\",internal_net=\"true\",device!=\"\"}[1m])",
     "legendFormat": "reads {{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "Saturation Disk(latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_disk_read_time_seconds_total[10s])) / \nsum by (instance,device) (rate(node_disk_reads_completed_total[10s]))",
     "legendFormat": "{{ instance }}_{{ device }} read latency"
    },
    {
     "expr": "sum by (instance,device) (rate(node_disk_write_time_seconds_total[10s])) / \nsum by (instance,device) (rate(node_disk_writes_completed_total[10s]))",
     "legendFormat": "{{ instance }}_{{ device }} write latency"
    }
   ]
  },
  {
   "title": "Traffic on real iface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m]) * 8",
     "legendFormat": "transmit {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m]) * 8",
     "legendFormat": "received {{ instance }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Packets on real iface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_packets_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m])",
     "legendFormat": "transmit {{ instance }}_{{ interface }}"
    },
    {
     "expr": "rate(container_network_receive_packets_total{id=\"/\",interface!~\"br.*\",internal_net=\"true\"}[1m])",
     "legendFormat": "received {{ instance }}_{{ interface }}"
    }
   ]
  },
  {
   "title": "Errors and drops packet on iface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance,device) (rate(node_network_transmit_errs_total{device!=\"lo\"}[1m]))",
     "legendFormat": "transmit errors {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum by (instance,device) (rate(node_network_receive_errs_total{device!=\"lo\"}[1m]))",
     "legendFormat": "received errors {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum by (instance,device) (rate(node_network_transmit_drop_total{device!=\"lo\"}[1m]))",
     "legendFormat": "transmit drop {{ instance }}_{{ device }}"
    },
    {
     "expr": "sum by (instance,device) (rate(node_network_receive_drop_total{device!=\"lo\"}[1m]))",
     "legendFormat": "received drop {{ instance }}_{{ device }}"
    }
   ]
  }
 ]
}